apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: phpmyadmin
  name: phpmyadmin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: phpmyadmin
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: phpmyadmin
    spec:
      containers:
      - image: phpmyadmin
        name: phpmyadmin
        imagePullPolicy: IfNotPresent
        envFrom:
          - configMapRef:
              name: phpmyadmin-configmap
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: phpmyadmin-configmap
  labels:
    app: phpmyadmin
data:
  PMA_ARBITRARY: "1"

---
apiVersion: v1
kind: Service
metadata:
  name: phpmyadmin-svc
  labels:
    app: phpmyadmin
spec:
  type: ClusterIP
  ports: 
    - port: 80
  selector:
    app: phpmyadmin